chromium: Upgrade to 148.0.7778.215 (#993)
Release notes:

148.0.7778.178:
https://chromereleases.googleblog.com/2026/05/stable-channel-update-for-desktop_0841193308.html

148.0.7778.215:
https://chromereleases.googleblog.com/2026/05/stable-channel-update-for-desktop_0877304591.html

Build and patch changes:
------------------------

New patches:

* chromium148-bytemuck-v1-remove-simd-LaneCount-usage.patch

  The build error with bytemuck-v1 returned for Chromium 148 and Rust 1.95.0

error[E0425]: cannot find type `LaneCount` in module `core::simd`
   --> ../../third_party/rust/chromium_crates_io/vendor/bytemuck-v1/src/zeroable.rs:234:15
    |
234 |   core::simd::LaneCount<N>: core::simd::SupportedLaneCount,
    |               ^^^^^^^^^ not found in `core::simd`

error[E0405]: cannot find trait `SupportedLaneCount` in module `core::simd`
   --> ../../third_party/rust/chromium_crates_io/vendor/bytemuck-v1/src/zeroable.rs:234:41
    |
234 |   core::simd::LaneCount<N>: core::simd::SupportedLaneCount,
    |                                         ^^^^^^^^^^^^^^^^^^ not found in `core::simd`

error[E0425]: cannot find type `LaneCount` in module `core::simd`
   --> ../../third_party/rust/chromium_crates_io/vendor/bytemuck-v1/src/pod.rs:155:15
    |
155 |   core::simd::LaneCount<N>: core::simd::SupportedLaneCount,
    |               ^^^^^^^^^ not found in `core::simd`

error[E0405]: cannot find trait `SupportedLaneCount` in module `core::simd`
   --> ../../third_party/rust/chromium_crates_io/vendor/bytemuck-v1/src/pod.rs:155:41
    |
155 |   core::simd::LaneCount<N>: core::simd::SupportedLaneCount,
    |                                         ^^^^^^^^^^^^^^^^^^ not found in `core::simd`

error: aborting due to 4 previous errors

  The patch previously added for Chromium 146 and then removed for 147
  need to be reverse-applied.

License changes:
----------------

None

Test dependencies:
------------------

* URI: git://git.openembedded.org/openembedded-core
  - branch: master
  - revision: be009835e779e9ad30ef595aed4131c3f2a792d6

* URI: git://git.openembedded.org/meta-openembedded
  - layers: meta-oe
  - branch: master
  - revision: 39321ae90b64e8f2bd890a2957a5f80e74d4de30

* URI: git://git.yoctoproject.org/meta-intel
  - branch: master
  - revision: 55e0ff278f7040dff5e453c509357820e8ce4c9b

* URI: https://github.com/agherzan/meta-raspberrypi
  - branch: master
  - revision: b4603a63b13e052a0f08761697fb5116a394bf64

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>