Revert "chromium: use COMPATIBLE_HOST instead of COMPATIBLE_MACHINE"
* COMPATIBLE_HOST is not good enough for some configurations:
  ERROR: chromium was skipped: incompatible with host arm-oe-linux-gnueabi (not in COMPATIBLE_HOST)

This reverts commit 7fb308d4f8d68d19a91daab8d33418cea8dea57b.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>