chromium-browser: add missing dependency on gperf-native
* chromium-wayland fails with:
  http://errors.yoctoproject.org/Errors/Details/132852/
  FAILED: gen/blink/platform/ColorData.cpp
  cd ../../third_party/WebKit/Source/platform; gperf "--key-positions=*"   -D -s 2 ColorData.gperf   "--output-file=../../../../out/Release/gen/blink/platform/ColorData.cpp"
  /bin/sh: 1: gperf: not found

* chromium fails with:
  http://errors.yoctoproject.org/Errors/Details/132851/
FAILED: gen/blink/core/CSSValueKeywords.cpp gen/blink/core/CSSValueKeywords.h
cd ../../third_party/WebKit/Source/core; python ../build/scripts/make_css_value_keywords.py css/CSSValueKeywords.in css/SVGCSSValueKeywords.in --output_dir ../../../../out/Release/gen/blink/core --gperf gperf
Traceback (most recent call last):
  File "../build/scripts/make_css_value_keywords.py", line 177, in <module>
    in_generator.Maker(CSSValueKeywordsWriter).main(sys.argv)
  File "TOPDIR/tmp-glibc/work/core2-64-oe-linux/chromium/52.0.2743.76-r0/chromium-52.0.2743.76/third_party/WebKit/Source/build/scripts/in_generator.py", line 95, in main
    writer.write_files(options.output_dir)
  File "TOPDIR/tmp-glibc/work/core2-64-oe-linux/chromium/52.0.2743.76-r0/chromium-52.0.2743.76/third_party/WebKit/Source/build/scripts/in_generator.py", line 71, in write_files
    self._write_file_if_changed(output_dir, generator(), file_name)
  File "../build/scripts/make_css_value_keywords.py", line 172, in generate_implementation
    gperf = subprocess.Popen(gperf_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, universal_newlines=True)
  File "TOPDIR/tmp-glibc/work/core2-64-oe-linux/chromium/52.0.2743.76-r0/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "TOPDIR/tmp-glibc/work/core2-64-oe-linux/chromium/52.0.2743.76-r0/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>