chromium: Upgrade to 148.0.7778.167 (#982)
chromium: Upgrade to 148.0.7778.167

Release notes:

148.0.7778.96:
https://chromereleases.googleblog.com/2026/05/stable-channel-update-for-desktop.html

148.0.7778.167:
https://chromereleases.googleblog.com/2026/05/stable-channel-update-for-desktop_12.html

Build and patch changes:
------------------------

Brought back gn-native renamed. gn in oe-core is not in lock-step with our chromium recipe version
but according to the original gn-native recipe, gn is not released
separately and Chromium is only ever tested with the gn version
it is shipped with.

Indeed, there is a weird compile time failure with Chromium version
148.0.7778.96 that is fixed by using a gn commit from master that's
newer than the one in wrynose.

Since the chromium recipes here and the gn recipe in openembedded-core
may diverge too much from each other, better safe than sorry, bring the
chromium specific gn-native recipe back in a way that does not clash
with the one in openembedded-core. Renaming it to chromium-gn-native
serves this purpose.

This reverts commit 3c65704bef ("gn-native: Remove recipe") and
updates it to the current chromium version.

Moved adding use_custom_libcxx=true to GN_ARGS later than the first
  GN_ARGS = "..."
line, which made
  GN_ARGS += "use_custom_libcxx=true"
ineffective.

Added patches:
* disable-sanitizer.patch

  Otherwise v8/src/sandbox/testing.cc fails to build:

| ../../v8/src/sandbox/testing.cc:43:10: fatal error: 'sanitizer/common_interface_defs.h' file not found
|    43 | #include <sanitizer/common_interface_defs.h>
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| 1 error generated.

  Remove the sanitizer enablement from v8/src/base/macros.h

Removed patches:
* use-adler2.patch - the adler2 rust module is used unconditionally
  in the new version

Modified patches:
* 0004-Delete-compiler-options-not-available-in-release-ver.patch

  A new compiler option not supported by current clang is used
  in Chromium 148, remove it.

* 0009-Adjust-the-Rust-build-to-our-needs.patch

  Adapted to Chromium 148

License changes:
----------------

Added licenses:

* third_party/android_deps/autorolled/committed/libs/com_google_android_play_review/LICENSE
* third_party/androidx/committed/libs/androidx_xr_arcore_arcore_projected/LICENSE
* third_party/dawn/third_party/EGL-Registry/LICENSE
* third_party/dawn/third_party/OpenGL-Registry/LICENSE
* third_party/harfbuzz/src/COPYING
* third_party/rust/chromium_crates_io/vendor/diplomat-runtime-v0_15/LICENSE-APACHE
* third_party/rust/chromium_crates_io/vendor/diplomat-v0_15/LICENSE-APACHE
* third_party/rust/chromium_crates_io/vendor/diplomat_core-v0_15/LICENSE-APACHE
* third_party/rust/chromium_crates_io/vendor/icu_experimental-v0_5/LICENSE
* third_party/rust/chromium_crates_io/vendor/icu_experimental_data-v0_5/LICENSE
* third_party/rust/chromium_crates_io/vendor/icu_experimental_data-v0_5/LICENSE
* third_party/rust/chromium_crates_io/vendor/jxl-v0_4/LICENSE;md5=6a905a337cc228a1f68f0b5416f52a7f \
* third_party/rust/chromium_crates_io/vendor/jxl_macros-v0_4/LICENSE;md5=6a905a337cc228a1f68f0b5416f52a7f \
* third_party/rust/chromium_crates_io/vendor/jxl_simd-v0_4/LICENSE;md5=6a905a337cc228a1f68f0b5416f52a7f \
* third_party/rust/chromium_crates_io/vendor/jxl_transforms-v0_4/LICENSE;md5=6a905a337cc228a1f68f0b5416f52a7f \
* third_party/rust/chromium_crates_io/vendor/memo-map-v0_3/LICENSE
* third_party/rust/chromium_crates_io/vendor/moxcms-v0_8/LICENSE-APACHE.md
* third_party/rust/chromium_crates_io/vendor/read-fonts-v0_38/LICENSE-APACHE
* third_party/rust/chromium_crates_io/vendor/skrifa-v0_41/LICENSE-APACHE
* third_party/rust/chromium_crates_io/vendor/strum-v0_28/LICENSE
* third_party/rust/chromium_crates_io/vendor/strum_macros-v0_28/LICENSE
* third_party/rust/chromium_crates_io/vendor/utf8_iter-v1/LICENSE-APACHE
* third_party/rust/chromium_crates_io/vendor/zip-v8/LICENSE
* third_party/rust/chromium_crates_io/vendor/zoneinfo64-v0_3/LICENSE
* third_party/webview2/LICENSE

Removed licenses:

* third_party/catapult/third_party/gsutil/LICENSE
* third_party/catapult/third_party/webtest/license.rst
* third_party/dawn/third_party/khronos/LICENSE
* third_party/harfbuzz-ng/src/COPYING
* third_party/material_design_icons/LICENSE
* third_party/rust/chromium_crates_io/vendor/diplomat-runtime-v0_14/LICENSE-APACHE
* third_party/rust/chromium_crates_io/vendor/diplomat-v0_14/LICENSE-APACHE
* third_party/rust/chromium_crates_io/vendor/diplomat_core-v0_14/LICENSE-APACHE
* third_party/rust/chromium_crates_io/vendor/icu_experimental-v0_4/LICENSE
* third_party/rust/chromium_crates_io/vendor/icu_experimental_data-v0_4/LICENSE
* third_party/rust/chromium_crates_io/vendor/jxl-v0_3/LICENSE;md5=6a905a337cc228a1f68f0b5416f52a7f \
* third_party/rust/chromium_crates_io/vendor/jxl_macros-v0_3/LICENSE;md5=6a905a337cc228a1f68f0b5416f52a7f \
* third_party/rust/chromium_crates_io/vendor/jxl_simd-v0_3/LICENSE;md5=6a905a337cc228a1f68f0b5416f52a7f \
* third_party/rust/chromium_crates_io/vendor/jxl_transforms-v0_3/LICENSE;md5=6a905a337cc228a1f68f0b5416f52a7f \
* third_party/rust/chromium_crates_io/vendor/moxcms-v0_7/LICENSE-APACHE.md
* third_party/rust/chromium_crates_io/vendor/read-fonts-v0_37/LICENSE-APACHE
* third_party/rust/chromium_crates_io/vendor/skrifa-v0_40/LICENSE-APACHE
* third_party/rust/chromium_crates_io/vendor/zip-v7/LICENSE
* third_party/rust/chromium_crates_io/vendor/zoneinfo64-v0_2/LICENSE
* third_party/xdg-utils/LICENSE

Updated licenses:

* third_party/android_deps/autorolled/committed/libs/com_google_android_play_core_common/LICENSE
* third_party/android_deps/autorolled/committed/libs/com_google_mlkit_genai_prompt/LICENSE
* third_party/icu/LICENSE

Test dependencies:
------------------

* URI: git://git.openembedded.org/openembedded-core
  - branch: wrynose
  - revision: 080e184ad9a07b469da7e8b045a93cefd5bf2438

* URI: git://git.openembedded.org/meta-openembedded
  - layers: meta-oe
  - branch: wrynose
  - revision: 420222862f5a6d95023b8f5f3b7e1808b2264ef9

* URI: git://git.yoctoproject.org/meta-intel
  - branch: master
  - revision: 2a8d44bf7b9faca3935b851107c70754e1cdcae3

* URI: https://github.com/agherzan/meta-raspberrypi
  - branch: master
  - revision: b4603a63b13e052a0f08761697fb5116a394bf64

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>

---------

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>