chromium: Disable use_sysroot
This variable is required to be unset so that we
can tell the system that we are using a different
newer C++ runtime library than the sysroot which
helps in compiling with clang also

Fixes link errors like
undefined reference to '__atomic_is_lock_free'

Signed-off-by: Khem Raj <raj.khem@gmail.com>