chromium: Fix the x86 build with GCC 8.
GCC 8 changed the behavior of alignof() to return the minimum alignment
required by the target ABI, instead of the preferred alignment. On x86, this
means alignof(int64_t) started returning 4 instead of 8, which led to a
build failure like

    In file included from ../../mojo/public/c/system/types.h:15,
    from ../../mojo/public/c/system/platform_handle.h:16,
    from ../../mojo/public/cpp/platform/platform_handle.h:12,
    from ../../mojo/public/cpp/platform/platform_channel_endpoint.h:10,
    from ../../mojo/core/connection_params.h:11,
    from ../../mojo/core/channel.h:15,
    from ../../mojo/core/node_channel.h:19,
    from ../../mojo/core/node_controller.h:25,
    from ../../mojo/core/node_controller.cc:5:
    ../../mojo/public/c/system/buffer.h:33:42: error: static assertion failed: int64_t has weird alignment
    MOJO_STATIC_ASSERT(MOJO_ALIGNOF(int64_t) == 8, "int64_t has weird alignment");
    ../../mojo/public/c/system/macros.h:15:53: note: in definition of macro 'MOJO_STATIC_ASSERT'
    #define MOJO_STATIC_ASSERT(expr, msg) static_assert(expr, msg)
    ^~~~
    ../../mojo/public/c/system/data_pipe.h:43:42: error: static assertion failed: int64_t has weird alignment
    MOJO_STATIC_ASSERT(MOJO_ALIGNOF(int64_t) == 8, "int64_t has weird alignment");
    ../../mojo/public/c/system/macros.h:15:53: note: in definition of macro 'MOJO_STATIC_ASSERT'
    #define MOJO_STATIC_ASSERT(expr, msg) static_assert(expr, msg)
    ^~~~
    ../../mojo/public/c/system/message_pipe.h:38:42: error: static assertion failed: int64_t has weird alignment
    MOJO_STATIC_ASSERT(MOJO_ALIGNOF(int64_t) == 8, "int64_t has weird alignment");
    ../../mojo/public/c/system/macros.h:15:53: note: in definition of macro 'MOJO_STATIC_ASSERT'
    #define MOJO_STATIC_ASSERT(expr, msg) static_assert(expr, msg)

The GCC change was actually correct, and clang was recently updated to
behave the same way. Backport a patch from upstream that fixes the Chromium
checks now that clang started hitting the same issues.

Fixes #192.

Signed-off-by: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>