chromium: Define stat and fstat to avoid conflicts
Fixes
../../third_party/lss/linux_syscall_support.h:1840:28: error: conflicting declaration of C function 'int sys_stat(const char*, kernel_stat64*)'
../../third_party/lss/linux_syscall_support.h:1840:28: error: conflicting declaration of C function 'int sys_fstat(int, kernel_stat64*)'

Signed-off-by: Khem Raj <raj.khem@gmail.com>