chromium: Ignore textrels on x86 build
building 32bit x86 results in textrels which I guess should be fixed
so here is a workaround until they are root caused and fixed.

Fixes build time QA error

ERROR: QA Issue: lib32-chromium-ozone-wayland: ELF binary /usr/bin/chromium has relocations in .text [textrel]

Signed-off-by: Khem Raj <raj.khem@gmail.com>