firefox: fix install issue and do_package_qa issues
1. Fix the firefox install missing the "usr/lib64/firefox/defaults/pref" directory issue.

| make[1]: Leaving directory `tmp/work/core2-64-wrs-linux/firefox/38.6.1esr-r0/mozilla-esr38/firefox-build-dir'
| install: target
'tmp/work/core2-64-wrs-linux/firefox/38.6.1esr-r0/image/usr/lib64/firefox/defaults/pref/' is not a directory: No such file or directory
| WARNING: tmp/work/core2-64-wrs-linux/firefox/38.6.1esr-r0/temp/run.do_install.329:1 exit 1 from

2. Add the "--libdir=${libdir}" into the mozconfig to make sure these
library files could be installed into the /usr/lib64 in the 64 bits OS.

WARNING: QA Issue: firefox: Files/directories were installed but not
shipped in any package:
  /usr/lib64/firefox
  /usr/lib64/firefox-devel-38.6/xpcom-config.h
  /usr/lib64/firefox-devel-38.6/idl
  /usr/lib64/firefox-devel-38.6/include
  /usr/lib64/firefox-devel-38.6/bin

3. Fix some do_package_qa warning issue which comes from the commit e045c68c41f65ba3b0b22d06022ea6c53e072ab5

NOTE: recipe firefox-38.6.1esr-r0: task do_package_qa: Started
ERROR: QA Issue: non -staticdev package contains static .a library:
firefox-dev path
'work/core2-64-wrs-linux/firefox/38.6.1esr-r0/packages-split/firefox-dev/usr/lib64/firefox-devel-38.6/sdk/lib/libcrmf.a'
[staticdev]
ERROR: QA run found fatal errors. Please consider fixing them.
ERROR: Function failed: do_package_qa
ERROR: Logfile of failure stored in:
tmp/work/core2-64-wrs-linux/firefox/38.6.1esr-r0/temp/log.do_package_qa.90631
NOTE: recipe firefox-38.6.1esr-r0: task do_package_qa: Failed

Signed-off-by: Guojian Zhou <guojian.zhou@windriver.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>