chromium: remove dependency on target python
* I plan to blacklist all target recipes in meta-python2 and leave
  only python-native (which is unfortunately still needed until:
  https://bugs.chromium.org/p/chromium/issues/detail?id=942720
  is completely resolved, now it fails with:
  python ../../third_party/blink/renderer/bindings/scripts/generate_bindings.py --web_idl_database gen/third_party/blink/renderer/bindings/web_idl_database.pickle --root_src_dir ../../ --root_gen_dir gen --output_core_reldir third_party/blink/renderer/bindings/core/v8/ --output_modules_reldir third_party/blink/renderer/bindings/modules/v8/ enumeration callback_function callback_interface interface namespace
  /usr/bin/env: /usr/bin/env: ‘python2’: No such file or directory
  ‘python2’: No such file or directory
  /usr/bin/env: ‘python2’: No such file or directory)

* setuptools.bbclass unfortunately pulls target python dependency
  but we actually need only the python-setuptools-native to fix:
  [33821/50143] python ../../components/schema_org/generate_schema_org_code.py --schema-file ../../third_party/schema_org/schema.jsonld --overrides-file ../../third_party/schema_org/overrides.jsonld --name-file gen/components/schema_org/schema_org_name_data.json --output-dir gen/components/schema_org --templates templates/schema_org_entity_names.cc.tmpl templates/schema_org_entity_names.h.tmpl templates/schema_org_enums.cc.tmpl templates/schema_org_enums.h.tmpl templates/schema_org_property_configurations.cc.tmpl templates/schema_org_property_configurations.h.tmpl templates/schema_org_property_names.cc.tmpl templates/schema_org_property_names.h.tmpl
  FAILED: gen/components/schema_org/schema_org_entity_names.h gen/components/schema_org/schema_org_entity_names.cc gen/components/schema_org/schema_org_property_configurations.h gen/components/schema_org/schema_org_property_configurations.cc gen/components/schema_org/schema_org_property_names.h gen/components/schema_org/schema_org_property_names.cc gen/components/schema_org/schema_org_enums.h gen/components/schema_org/schema_org_enums.cc
  python ../../components/schema_org/generate_schema_org_code.py --schema-file ../../third_party/schema_org/schema.jsonld --overrides-file ../../third_party/schema_org/overrides.jsonld --name-file gen/components/schema_org/schema_org_name_data.json --output-dir gen/components/schema_org --templates templates/schema_org_entity_names.cc.tmpl templates/schema_org_entity_names.h.tmpl templates/schema_org_enums.cc.tmpl templates/schema_org_enums.h.tmpl templates/schema_org_property_configurations.cc.tmpl templates/schema_org_property_configurations.h.tmpl templates/schema_org_property_names.cc.tmpl templates/schema_org_property_names.h.tmpl
  Traceback (most recent call last):
    File "../../components/schema_org/generate_schema_org_code.py", line 22, in <module>
      env = Environment(loader=PackageLoader('generate_schema_org_code', ''))
    File "/OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/chromium-x11/89.0.4389.82-r0/chromium-89.0.4389.82/components/schema_org/../../third_party/jinja2/loaders.py", line 222, in __init__
      from pkg_resources import DefaultProvider, ResourceManager, \
  ImportError: No module named pkg_resources

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>