chromium: update from 101.0.4951.54 to 103.0.5060.129
Manually refit patches to deal with upstream changes:
   0001-limit-number-of-LTO-jobs.patch
   0008-avoid-link-latomic-failure-on-CentOS-8-host.patch
   0009-nomerge-attribute-on-declaration-is-only-available-s.patch
   meta-chromium/recipes-browser/chromium/files/0014-Fix-no-member-named-tie-in-namespace-std.patch
and for musl:
   0001-mallinfo-implementation-is-glibc-specific.patch
   0009-provide-res_ninit-and-nclose-APIs-on-non-glibc-linux.patch

Remove upstreamed commit:
   68c9c63c0b148 Fix no member named 'tie' in namespace 'std'

Backport an upstream change to fix:
   error: unknown argument: '-no-opaque-pointers'
using patch:
   0013-clang-Re-enable-opaque-pointers.patch

Remove the temporary ozone VA-API patch:
   0001-ozone-add-va-api-support-to-wayland.patch
since it appears that upstream changes such as:
   7caf517265ff5   2022-05-12   ozone/wayland: use struct traits instead of TypeConverter
   e59f9b27202eb   2022-05-11   ozone/wayland: remove @ + id from the crash key
   d02dcd37ec440   2022-05-05   ozone/wayland: check fences retired
   05e27516ae15d   2022-05-05   ozone/wayland: do not issue glFlush if image flush is available.
   a21df4c9b3a2d   2022-05-04   lacros: ozone/wayland: pass overlay background information
   a6c9bcad7abab   2022-04-22   ozone/wayland: can reuse the same buffer handle
   05ae925bd7c17   2022-04-20   ozone/wayland: do not create wl_buffers unless the pixmap is scheduled
   701c25f8b3dca   2022-04-20   ozone/wayland: fix setting opaque region
have implemented some of the feature that Maksim mentioned in the patch log.

License changes:
----------------

    Removed licenses:
      * ios/third_party/native_closure_compiler/LICENSE
      - Remove js_compile.gni
      - https://chromium-review.googlesource.com/c/chromium/src/+/3595761
      * third_party/libXNVCtrl/LICENSE
      - Remove third_party/libXNVCtrl/, which is duplicated elsewhere
      - https://chromium-review.googlesource.com/c/chromium/src/+/3449618
      * third_party/opencv/src/LICENSE
      - Remove legacy visual model for Client Side Phishing Detection
      - https://chromium-review.googlesource.com/c/chromium/src/+/3558834
      * third_party/usrsctp/LICENSE
      - Remove third_party/usrsctp
      - https://chromium-review.googlesource.com/c/chromium/src/+/3568252

    Updated licenses:
      * third_party/android_deps/libs/com_google_android_gms_play_services_auth_api_phone/LICENSE
      * third_party/android_deps/libs/com_google_android_gms_play_services_auth_base/LICENSE
      * third_party/android_deps/libs/com_google_android_gms_play_services_auth/LICENSE
      * third_party/android_deps/libs/com_google_android_gms_play_services_base/LICENSE
      * third_party/android_deps/libs/com_google_android_gms_play_services_basement/LICENSE
      * third_party/android_deps/libs/com_google_android_gms_play_services_instantapps/LICENSE
      * third_party/android_deps/libs/com_google_android_gms_play_services_location/LICENSE
      * third_party/android_deps/libs/com_google_android_gms_play_services_tasks/LICENSE
      * third_party/android_deps/libs/com_google_android_gms_play_services_vision_common/LICENSE
      * third_party/android_deps/libs/com_google_android_gms_play_services_vision/LICENSE
      - Rolling all public GMSCore libraries
      - https://chromium-review.googlesource.com/c/chromium/src/+/3551907
      * third_party/boringssl/src/third_party/fiat/LICENSE
      - Update fiat-crypto.
      - https://boringssl-review.googlesource.com/c/boringssl/+/52045
      * third_party/ffmpeg/CREDITS.chromium
      - Add update configs for m102 ffmpeg roll.
      - https://chromium.googlesource.com/chromium/third_party/ffmpeg.git/+/be271ca404c46aa2504092904a763f927c1e79e1
      - Drop avsscanf.c from the build since we don't use it.
      - https://chromium.googlesource.com/chromium/third_party/ffmpeg.git/+/32b2d1d52612e47531df9289e3f5fdd5447507dd
      * third_party/icu/LICENSE
      - Update ICU to ICU 71-1
      - https://chromium-review.googlesource.com/c/chromium/deps/icu/+/3579992
      * third_party/zlib/LICENSE
      - [zlib] Re-sync with zlib 1.2.12, patch 15 of N
      - https://chromium-review.googlesource.com/c/chromium/src/+/3611239

Test-built:
-----------

* chromium-ozone-wayland:
 - master, clang,    MACHINE=qemux86-64, qemuarm64, qemuarm
 - dunfell, clang**, MACHINE=qemux86-64, qemuarm64, qemuarm

* chromium-x11
 - master, clang,    MACHINE=qemux86-64, qemuarm64, qemuarm
 - kirkstone, clang, MACHINE=qemux86-64, qemuarm64, qemuarm
 - dunfell, clang**, MACHINE=qemux86-64, qemuarm64, qemuarm

** Please note that Chromium requires clang version to be >= 12.
For that, when on dunfell branch, use meta-clang/clang12 branch.

Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>