chromium: include uint64_t in sim_hash namespace
Previously failing to compile sim_hash.h with error
| In file included from ../../components/federated_learning/sim_hash.cc:5:
| ../../components/federated_learning/sim_hash.h:20:15: error: unknown type name 'uint64_t'
|   void SetBit(uint64_t pos);

Patch 0001-Fix-lack-of-uint64_t-in-sim_hash-namespace.patch fixes
this error, but should be removed as soon as the chromium version
is updated to 86.x.xxxx.xx+.

Signed-off-by: Stacy Gaikovaia <Stacy.Gaikovaia@windriver.com>