cbindgen: upgrade to 0.23.0
* the old version is not compatible with rust-1.60 currently in oe-core and firefox
  build fails with:

 0:01.30 xpcom/base/gk_rust_utils_ffi_generated.h.stub
 0:01.69 thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/bindgen/cargo/cargo.rs:19:16
 0:01.69 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 0:01.69 make[4]: *** [backend.mk:41: .deps/gk_rust_utils_ffi_generated.h.stub] Error 101
 0:01.69 make[3]: *** [/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/config/recurse.mk:101: xpcom/base/export] Error 2
 0:01.69 make[2]: *** [/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/config/recurse.mk:34: export] Error 2
 0:01.69 make[1]: *** [/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/config/rules.mk:413: default] Error 2

and similarly for .deps/ServoStyleConsts.h.stub and .deps/webrender_ffi_generated.h.stub

It's actually cbindgen-native call from RunCbindgen.py as in:

/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/firefox-build-dir/_virtualenvs/init/bin/python  -m mozbuild.action.file_generate /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/layout/style/RunCbindgen.py generate gk_rust_utils_ffi_generated.h .deps/gk_rust_utils_ffi_generated.h.pp .deps/gk_rust_utils_ffi_generated.h.stub /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/xpcom/rust/gkrust_utils

but even with RUST_BACKTRACE=full it doesn't show much:

/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/recipe-sysroot-native/usr/bin/cbindgen --clean /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/toolkit/library/rust/ --lockfile /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/Cargo.lock --crate gkrust_utils
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/bindgen/cargo/cargo.rs:19:16
stack backtrace:
   0:     0x55b344f0451a - <unknown>
   1:     0x55b344f20c0e - <unknown>
   2:     0x55b344eea8f0 - <unknown>
   3:     0x55b344ef1555 - <unknown>
   4:     0x55b344ef128d - <unknown>
   5:     0x55b344ef1b73 - <unknown>
   6:     0x55b344f049b1 - <unknown>
   7:     0x55b344f04644 - <unknown>
   8:     0x55b344ef1690 - <unknown>
   9:     0x55b344c41522 - <unknown>
  10:     0x55b344c41461 - <unknown>
  11:     0x55b344d6b211 - <unknown>
  12:     0x55b344cd86e6 - <unknown>
  13:     0x55b344cfdb91 - <unknown>
  14:     0x55b344d6c21d - <unknown>
  15:     0x55b344d3f934 - <unknown>
  16:     0x55b344d3f1f6 - <unknown>
  17:     0x55b344d6aaec - <unknown>
  18:     0x55b344d86fe1 - <unknown>
  19:     0x55b344d60113 - <unknown>
  20:     0x55b344d732c9 - <unknown>
  21:     0x55b344ee58a1 - <unknown>
  22:     0x55b344d88ca1 - <unknown>
  23:     0x7fea107194fb - __libc_start_call_main
  24:     0x7fea107195b9 - __libc_start_main@@GLIBC_2.34
  25:     0x55b344c41cd1 - <unknown>
  26:                0x0 - <unknown>

there is another weird error:

 0:00.76 Traceback (most recent call last):
 0:00.76   File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
 0:00.76     "__main__", fname, loader, pkg_name)
 0:00.76   File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
 0:00.76     exec code in run_globals
 0:00.76   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/action/file_generate.py", line 120, in <module>
 0:00.77     sys.exit(main(sys.argv[1:]))
 0:00.77   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/python/mozbuild/mozbuild/action/file_generate.py", line 60, in main
 0:00.77     ('.py', 'r', imp.PY_SOURCE))
 0:00.77   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/accessible/xpcom/AccEventGen.py", line 29, in <module>
 0:00.77     p = xpidl.IDLParser()
 0:00.77   File "/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/xpcom/idl-parser/xpidl/xpidl.py", line 1809, in __init__
 0:00.77     optimize=1)
 0:00.77   File "/OE/build/test-oe-build-time/poky/bitbake/lib/ply/yacc.py", line 3064, in yacc
 0:00.77     signature = pinfo.signature()
 0:00.77   File "/OE/build/test-oe-build-time/poky/bitbake/lib/ply/yacc.py", line 2813, in signature
 0:00.77     return sig.digest()
 0:00.77 UnboundLocalError: local variable 'sig' referenced before assignment

Which is caused by python2 from firefox venv trying to use bitbake's ply and
it doesn't like usedforsecurity=False added for fips in:
https://git.openembedded.org/bitbake/commit/lib/ply/yacc.py?id=af866dd077867cba0129757bfcc689551445e9d7

$ /OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.9.0esr-r0/firefox-68.9.0/firefox-build-dir/_virtualenvs/init/bin/python
Python 2.7.18 (default, May 16 2022, 14:07:21)
[GCC 11.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import hashlib
>>> sig = hashlib.new('MD5', usedforsecurity=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __hash_new() got an unexpected keyword argument 'usedforsecurity'

but that's not fatal (and I still only care about firefox build time, wouldn't
use such old version on any device).

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>