firefox: Update to 52.1.2esr using debian's patchset
* Update Firefox to 52.1.2esr
* Update respective l10n recipes for 52.1.2esr
* Fix obsolete configure options in mozilla.bbclass
* Remove TARGET_CC_ARCH because it causes a configure error:
  > mozbuild.configure.options.InvalidOptionError: CC takes 1 value
  In addition this work around seems not necessary anymore because it was
  introduced for built-in nss which isn't used in the current recipe.

Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>