firefox: add CLEANBROKEN
* breaks devtool:
NOTE: recipe firefox-68.0esr-r0: task do_buildclean: Started
ERROR: firefox-68.0esr-r0 do_buildclean: oe_runmake failed
ERROR: firefox-68.0esr-r0 do_buildclean: Execution of '/OE/build/test-oe-build-time/poky/build/tmp/work/core2-64-poky-linux/firefox/68.0esr-r0/temp/run.do_buildclean.62921' failed with exit code 1:
./mach clobber
Traceback (most recent call last):
  File "./mach", line 86, in <module>
    main(sys.argv[1:])
  File "./mach", line 78, in main
    mach = get_mach()
  File "./mach", line 68, in get_mach
    mach = check_and_get_mach(dir_path)
  File "./mach", line 42, in check_and_get_mach
    return load_mach(dir_path, mach_path)
  File "./mach", line 30, in load_mach
    return mach_bootstrap.bootstrap(dir_path)
  File "/OE/build/test-oe-build-time/poky/build/workspace/sources/firefox/build/mach_bootstrap.py", line 364, in bootstrap
    driver.load_commands_from_file(os.path.join(mozilla_dir, path))
  File "/OE/build/test-oe-build-time/poky/build/workspace/sources/firefox/python/mach/mach/main.py", line 266, in load_commands_from_file
    imp.load_source(module_name, path)
  File "/OE/build/test-oe-build-time/poky/build/workspace/sources/firefox/build/valgrind/mach_commands.py", line 17, in <module>
    from mozbuild.base import (
  File "/OE/build/test-oe-build-time/poky/build/workspace/sources/firefox/build/mach_bootstrap.py", line 393, in __call__
    module = self._original_import(name, globals, locals, fromlist, level)
  File "/OE/build/test-oe-build-time/poky/build/workspace/sources/firefox/python/mozbuild/mozbuild/base.py", line 23, in <module>
    from mach.mixin.process import ProcessExecutionMixin
  File "/OE/build/test-oe-build-time/poky/build/workspace/sources/firefox/build/mach_bootstrap.py", line 393, in __call__
    module = self._original_import(name, globals, locals, fromlist, level)
  File "/OE/build/test-oe-build-time/poky/build/workspace/sources/firefox/python/mach/mach/mixin/process.py", line 30, in <module>
    raise Exception('Could not detect environment shell!')
Exception: Could not detect environment shell!
make: *** [GNUmakefile:12: clean] Error 1
WARNING: exit code 1 from a shell command.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>