firefox: update 136.0.1 -> 136.0.3, add musl support
Notes on musl changes:
"--disable-jemalloc": it can't compile on musl, missing mutex type

"-Wl,-rpath,${libdir}/firefox": when starting ff, it can't find libraries
if they are not in the standard locations defined in /etc/ld-musl... config.
Adding this rpath helps with this.

"--disable-sandbox": otherwise when it starts, it keeps throwing thousands
of "Sandbox: seccomp sandbox violation" errors, and refuses to load any
pages

libexecinfo dependency: to avoid compile time error:
system_wrappers/execinfo.h:3:15: fatal error: 'execinfo.h' file not found

Add patch to guard glibc-only code-paths to avoid trying to compile
then with musl.

Beside this, due to the number of tests, refactor the github workflows also:
instead of a separate workflow file, use matrix strategy to execute all
combinations of tests.