chromium: use bundled freetype
* Fixes https://github.com/OSSystems/meta-browser/issues/569

* because the current skia codebase expects freetype newer than latest
  2.11 release from freetype upstream

* chromium-ozone-wayland as well as chromium-x11 with honister based builds:

  ../../third_party/skia/src/ports/SkFontHost_FreeType.cpp:1110:13: error: unknown type name 'FT_ClipBox'
              FT_ClipBox colrGlyphBbox;
              ^

  and

  ../../third_party/skia/src/ports/SkFontHost_FreeType_common.cpp:438:14: error: use of undeclared identifier 'FT_COLR_COMPOSITE_PLUS'
  ../../third_party/skia/src/ports/SkFontHost_FreeType_common.cpp:1009:5: error: unknown type name 'FT_ClipBox'

  FT_COLR_COMPOSITE_PLUS is defined in bundled freetype:
  ./third_party/freetype/src/include/freetype/ftcolor.h:    FT_COLR_COMPOSITE_PLUS           = 12,
  and added to upstream freetype in:
  https://github.com/freetype/freetype/commit/e40ae7569aa4ef591f66ff9066df2f91de75bb77#diff-81347c1a5d4e3ac2906ad0df93738046c8c139135e2b3c1fbfe0ae22f9de929c
  but isn't included in 2.11 version currently in oe-core:
  https://github.com/freetype/freetype/blob/VER-2-11-0/include/freetype/ftcolor.h

  Similarly FT_ClipBox was added after 2.11 in
  https://github.com/freetype/freetype/commit/47cf8ebf4a78ed42da455a98d77a92ce6a180d78#diff-81347c1a5d4e3ac2906ad0df93738046c8c139135e2b3c1fbfe0ae22f9de929c

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>