chromium: fix x11 dependency brought by at-spi2-core package.
This patches fixes the following error:

ERROR: Nothing PROVIDES 'at-spi2-core' (but
/home/msisov/code/meta-browser-release/recipes-browser/chromium/chromium-ozone-wayland_71.0.3578.98.bb
DEPENDS on or otherwise requires it)
at-spi2-core was skipped: missing required distro feature 'x11' (not in
DISTRO_FEATURES)
NOTE: Runtime target 'chromium-ozone-wayland' is unbuildable,
removing...
Missing or unbuildable dependency chain was: ['chromium-ozone-wayland',
'at-spi2-core']
ERROR: Required build target 'agl-demo-platform' has no buildable
providers.
Missing or unbuildable dependency chain was: ['agl-demo-platform',
'chromium-ozone-wayland', 'at-spi2-core']

Basically, Wayland does not seem to have a good accesibility support
as I was told. Thus, if distro does not provide x11 package, disable
atk support in the Chromium browser.

Signed-off-by: Maksim Sisov <msisov@igalia.com>